[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
  
[[redirects]]
  from = "https:framelo.netlify.com/*"
  to = "https://www.framelo.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
